### ISSUE TITLE
Changes to data manipulation

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#101]
As a result of review of #90 

### Coupling

* [x] Remove the `Total ${unit}` column from `logstoAggregatedData` (move it to `aggregatedToTableData`): this couples the aggregate data structure too closely to the design of the tables; it should also support the charts which won't have this data point.

* [x] Don't pass column headers to `logsToAggregateData`: `AggregateData` is an intermediate data structure that should be de-coupled from table-specific considerations. Instead just identify the fields to use as column headers (already done via `tableTypes`) and use those to accumulate the columns represented in the log data. Specific column headers/ordering can be specified in the next step `aggregatedToTableData`, and should replace empty or undefined keys with `0`.

### Composition

* [x] Compose the `useRequest` hook with the `useAggregateData`

**Comment by eliascodes** [comment]
After taking a closer look at the code (after actually having to change it in #117), I have the following comments.

Related to my second point above, ultimately what we have is a process of _projecting_ a list of objects onto a single "object". In `logsToAggregatedData` we want to arrive at a point where all our log data is combined in a data structure that has, at least, _rows_ and _cells_.
```ts
type Cell = string | Duration;

interface Row extends Dictionary {}

type TableContent = Row<Cell>[];

interface Table {
  headers: string[];
  rows: TableContent;
}

interface Projection {
  <T>(rowId: string, colId: string, combinator: (a: T, b: T) => T, data: Dictionary<T>[]): TableContent;
}
```
We can additionally define functions that map over `Row`s and `Cell`s:
```ts
interface mapRow {
  (f: (c: Cell) => Cell, r: Row): Row;
}

interface mapTableContent {
  (f: (r: Row) => Row, rs: TableContent): TableContent;
}
```
These can be used to implement all the date string transformations and the totals calculation in `aggregateToTableData`, and also to pad the columns with default values (e.g. zeroes for columns with no data).

The point of this is that if we identify and extract the more primitive concepts, it becomes much easier to (1) see whats going on, (2) extend it and (3) re-use it.

The use of `Table` in the type names is mostly out of a lack of a better name for a labelled 2D grid, but obviously these shouldn't necessarily be conceptually bound to the "tables" we see in the actual pages (as may become clear once we start doing charts stuff).

**Comment by astroash** [comment]
- what does `combinator` describe in the above?
- how does this differ from the deriving column headers from the available data as previously discussed?

**Comment by eliascodes** [comment]
> what does combinator describe in the above?

A generic way of doing what you're doing [here](https://github.com/TwinePlatform/twine-monolith/blob/cbd3fc7017982e3ab55c2db7ec2b07deb59e5de9/dashboard-app/src/util/dataManipulation/logsToAggregatedData.ts#L57-L66)

> how does this differ from deriving column headers from the available data as previously discussed?

It doesn't, unless I misunderstand what you mean.
