### ISSUE TITLE
Data table dates are "invalid"

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#105]
Presumably as a result of #90

Found on `twine-dashboard-qa` and `twine-dashboard-staging`. This appears not to be a problem when I try to reproduce locally, suggesting an issue with the data itself?

<img width="1031" alt="Screenshot 2019-05-22 at 14 42 03" src="https://user-images.githubusercontent.com/12719553/58179304-d6fc1600-7c9f-11e9-8759-9e07b1357fd7.png">

**Comment by astroash** [comment]
Note this bug is firefox specific
