### ISSUE TITLE
🔐 session management for dashboard

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#115]
Twine Plaform is comprised of 4 apps and 5 user types

## Users & Apps
User types:
- `TWINE_ADMIN`
- `CB_ADMIN`
- `VOLUNTEER_ADMIN`
- `VOLUNTEER`
- `VISITOR`

3 web apps:
- Visitor App (visitor.twine-together.com)
  supports login for:
	- `CB_ADMIN`
  supports QR code scanning for:
	- `VISITOR`
- Admin Dashboard (admin.twine-together.com)
  supports login for:
	- `TWINE_ADMIN`
- Volunteer Dashboard (data.twine-together.com)
  supports login for:
	- `CB_ADMIN`
	- `VOLUNTEER_ADMIN`

1 native mobile app:
- Volunteer App (downloadable on app/play store)
  supports login for:
	- `CB_ADMIN`
	- `VOLUNTEER_ADMIN`

## Definitions
* **Session**: the duration of time for which a user is authenticated to use an app
* **Login**: the act of a user entering their email and password

## Session Options for the Dashboard
**NOTE**: When considering these options, only the web-apps are relevant. The native app necessarily uses a separate mechanism and will always require a separate login.

### 1️⃣ Global session (current default)
If a user logs into one app, they begin a _global_ session. This session is valid across all twine web-apps. This means, for example, user may log into one app on their web-browser, then navigate to a different app without having to log in again.

Example:
- `CB_ADMIN` logs into visitor app on web browser
- `CB_ADMIN` navigates to dashboard
- `CB_ADMIN` is able to use dashboard without having to log in

This is potentially problematic: `CB_ADMIN` users log into the visitor app on a tablet that is left front of house (to be used by visitors). This means it's possible (though unlikely) that a visitor will navigate to the dashboard and be able to see volunteer data.

### 2️⃣ App session: require login
This will separate sessions for all apps. A user will have to log into each new app that they wish to use.

User Flow:
- `CB_ADMIN` has previously logged into visitor app.
- `CB_ADMIN` goes to volunteer dashboard and has to enter their details again.

## Session length
The amount time after which a session expires may be configured. Currently it stands (arbitrarilty) at 1 week. A value should be selected that balances user experience with security.

## Time Estimates

**Option 1** - 0 days (current setup)
**Option 2** - 5 days

It is possible to release under "Option 1", and move over to "Option 2" at a later date. This will not cause a disruption to usage.

The above is development effort, not elapsed time.

**Comment by astroash** [comment]
to be reviewed in next planning session 28/05/19

**Comment by milski360** [comment]
I think let's release under Option 1 and move over to Option 2 in a future sprint.

**Comment by eliascodes** [comment]
This is actually done because we do not set the `domain` value of the cookie, so they do not carry across sub-domains.
