### ISSUE TITLE
Create chart filtering component

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#127]
Data fed through to charts needs to be filtered by activity/volunteer. See user stories 006B and 007B.

**Comment by astroash** [comment]
This functionality is covered by chartjs:

![filter_users](https://user-images.githubusercontent.com/14337958/58568941-75a2ec80-8235-11e9-9a42-269b7afaf50a.gif)

**Comment by astroash** [comment]
@eliascodes are you happy for this to be closed?

**Comment by eliascodes** [comment]
I guess so. It's not clear to me that the out of the box functionality totally satisfies the features specified in the user stories, but I guess we can resurrect this in that case.
