### ISSUE TITLE
Persistence of filter data between chart/table

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#163]
Steps: 
- Browse to the Volunteer chart tab. 
- I use the chart filter to deselect some people. 
- Click the table tab and then click the chart tab again.  

Expected: The previous filter criteria i created to persist.
Actual: The previous filter is gone and the default filter exists

**Comment by astroash** [comment]
Re conversation on consistency of filtering on tables & graphs:

<img width="334" alt="Screen Shot 2019-06-21 at 17 15 37" src="https://user-images.githubusercontent.com/14337958/59925057-46ecf000-9448-11e9-9126-f441b190ca11.png">
