### ISSUE TITLE
Un-expressed/un-enforced dependency between chart/legend data

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#187]
Related to #186 

See comment:

> I'm merging for expediency, but this seems to indicate a dependency between the legend data and chart data that isn't enforced. They should be derived from the same source in the same way/same order, so that this otherwise obtuse .reverse isn't necessary.

**Comment by astroash** [comment]
They are derived from the same source. Chartjs just starts drawing from the last dataset, so it needs to be reversed.

**Comment by astroash** [comment]
@eliascodes can this be closed?

**Comment by eliascodes** [comment]
I'll add a more detailed comment explaining the `reverse`, then close this
