### ISSUE TITLE
📊 Create dashboard widgets

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#192]

**Comment by astroash** [comment]
user stories being updated

**Comment by eliascodes** [comment]
Suggested component interface:
```ts
type TileProps = {
  topText: string
  dataPointOne: string[]
  dataPointOneLabel: string
  dataPointTwo: number | string[]
  dataPointTwoLabel: string
};
```
Where `dataPointOne` is the list of activities or months (US010A/B) or empty (US010C), `dataPointOneLabel` is the text just above that, `dataPointTwo` is the number of hours (US010A/B) or the list of volunteer names (US010C), and `dataPointTwoLabel` is the text just below the yellow line.

The naming convention `dataPoint<X>` is not very good so open to suggestions on this, but from what I can see this is the data that's needed.

Alternatively:
```ts
type TileDataPoint<T> = {
  label: string
  data: T
};

type TileProps = {
  topText: string
  one: TileDataPoint<string[]>
  two: TileDataPoint<number | string[]>
};
```

Again though, `one` and `two` are poorly named.

**Comment by eliascodes** [comment]
- `Polaroid` component to accept children
- `topText` prop to be split into two to support bolding part of it
- Additional prop to indicate different layout mode for `two.data`

**Comment by astroash** [comment]
Updated interface suggestion:
```js
type TileDataPoint<T> = {
  label: string
  data: T
};

export type LayoutMode = 'number' | 'text';

type TileProps = {
  topText: string []
  left: TileDataPoint<string[]>
  right: TileDataPoint<number | string[]> & { layoutMode: LayoutMode }
  bottomText: string []
};
```

See #219 for working example

**Comment by eliascodes** [comment]
`layoutMode` isn't used in #219

**Comment by astroash** [comment]
> layoutMode isn't used in #219

😅 not yet, I was trying to throw something up quickly as I knew you were working on related work. This is a demo of what it would look like when set to `'number'`, `MiddleTopRightContainer` will return something different if set to `'text'`

**Comment by eliascodes** [comment]
So I'm assuming the code will look something like:
```ts
if (props.layoutMode === 'number') {
  return formatNumberData(props.right.data);
} else if (props.layoutMode === 'text') {
  return formatTextData(props.right.data);
}
```

This will actually cause _more_ TS issues than relying on type inference, because there is a relationship between the type of `right.data` and the value of `right.layoutMode` that is unexpressed in the type declarations, so you will need to use some `as` type-casting in order to make the function calls work.

e.g.
```ts
if (props.layoutMode === 'number') {
  return formatNumberData(props.right.data as number);
} else if (props.layoutMode === 'text') {
  return formatTextData(props.right.data as string[]);
}
```

Instead if you just rely on type inference, it'll be:
```ts
if (typeof props.right.data === 'number') {
  // TS knows this is a number now
  return formatNumberData(props.right.data);
} else if (Array.isArray(props.right.data)) {
  // TS knows this is a string[] now
  return formatTextData(props.right.data);
}
```

**Comment by astroash** [comment]
IMO I am less interested in typescript convenience, and more interested in designing an interface which is explicitly configurable. I'll outline how this could work n push to the above PR.

**Comment by eliascodes** [comment]
Alternative: define two different `Tile` components, one which handles `number`, one which handles `string[]`. We're never choosing between the two dynamically; we always know which one we want where.

Then we have:
```ts
type TileDataPoint<T> = {
  label: string
  data: T
};

type TileProps<T, U> = {
  topText: string
  one: TileDataPoint<T>
  two: TileDataPoint<U>
  bottomText: string[]
};

type NumberTileProps = TileProps<string[], number>
type TextTileProps = TileProps<string[], string[]>
```

Then we don't have an implicit relationship between props, there's no configurability, and the components are more declarative.

**Comment by astroash** [comment]
Yeah, that's a nice solution, happy to go with that. Also noticed I was taking bottom text from the designs not the user stories, this line has been dropped. I'll leave the layout styling for it (for future iterations), but we either set the prop to optional or drop it.

**Comment by astroash** [comment]
@eliascodes do you have a preference on how to represent no data. Options:
- separate component
- dynamically displayed when data options are empty (`topText` will need to be optional in this case)
- configured with a prop

**Comment by eliascodes** [comment]
What case in the user stories are you thinking of? When no data is available, we still display the top text (see the design concept in US 010A).

In the case of no data I was imagining `left.data` to be an empty array and `left.label` to be `"No data available"`.

However, also happy to go with a separate component, if you feel that's more consistent with the rest of our approach to this.

**Comment by astroash** [comment]
> When no data is available, I think we still display the top text (see the design concept in US 010A).

Yup you're right. 

Layout for US010C is different for the no data view, so it will make sense to handle the no data view text values in data manipulation.
