### ISSUE TITLE
🔐 Access to API for external users 

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#199]
We have some of the infrastructure from frontline.

- amend external strategy to include cb in credentials
- amend hooks to have clause for external users eg is_child_org
- create scope `VISITOR_APP_CB_ACCESS`
- add scope to requested routes
- add entry to `api_token` table with:
```
 api_token_name = cb’s name
 api_token_access = VISITOR_APP_CB_ACCESS
 api_token = bcrypt hash of a token
```
- test it

estimated 3 days work

**Comment by eliascodes** [comment]
Not sure how you'd imagined this bit:

> amend external strategy to include cb in credentials

Currently the `api_token` table isn't linked to any other tables in the DB.

I think probably the simplest thing to do is add a FK from the `api_token` table to the `user_account` table. In this implementation, each token would grant access to all of the users organisations (currently, and for the forseeable future, only one), and have its full permissions set. Then we don't need to add any new scopes to routes.

We also don't need to pay attention to `api_token_access`, so we could get rid of it.

**Comment by astroash** [comment]
> I think probably the simplest thing to do is add a FK from the api_token table to the user_account table.

I don’t like this idea. This will make this a one use table, what happens when we want to support another service like frontline?

I’d imagined it to match on CB name which is equally imperfect as it will rely on application code to enforce the constraint.

**Comment by eliascodes** [comment]
> what happens when we want to support another service like frontline?

Those two things are quite different. One is an external third party wanting to access platform data, the other is a registered user wanting to access their own data. We no longer have any foreseeable use cases that require the former. If we do ever need to support both I don't think there's any reason we need to use the same table, as they'd probably have fairly different requirements.

The use case we're addressing, as far as I can see, is that of requiring a personal access token (necessarily tied to an account). I think loosely following the model of the [Github personal access token](https://github.com/settings/tokens) seems pretty reasonable.

**Comment by eliascodes** [comment]
I did a version of your original solution which is living here, since it was quicker to implement: https://github.com/TwinePlatform/twine-monolith/tree/api/opt-1-external-access

I think given that we are doing this for only one organisation so far, it's fine. However, if/when this becomes a feature we actually want to offer more widely, I think the personal-access-token model is worth implementing properly.
