### ISSUE TITLE
Session mgmt

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#207]
### Business Decisions
1. Should existing user sessions be preserved?
   - If no, all users will be logged out, and have to log in again (once)
   - If yes, users will be able to continue using the apps and will be gradually migrated onto the new session system
   - If yes, this will add ~30% to the development effort
2. Should old sessions be monitored?
   - Allows us to check how long until old system can be retired
   - Adds to development effort
   - Potentially limited use, if transition period is on order of 1-2 weeks.

### Technical Decisions
1. If existing sessions are preserved, two options:
   1. Create new scheme/strategy which handles both JWT and session IDs
   2. Create new scheme/strategy which handles session IDs, add this strategy to all relevant API routes
2. How to reliably test before deployment?

#### Migration under Option 1
The `validate` method:
  - checks for presence of session cookie.
    - If present and valid, continue.
    - If present and invalid, 401.
    - If not present, 401.
  - checks for presence of JWT.
    - If present and valid, sets a session cookie.
    - If present and expired, 401.
    - If present and invalid, 401.
    - If not present, 401.
  - 401

Login route is changed to:
  - Authenticate against the new strategy in `try` mode
  - If authenticated with JWT:
     - Set session ID
     - 200
  - If authenticated with session ID:
     - 200
  - Else evaluate payload:
     - If valid, create new session, set session ID cookie
     - Else 401

Only users presenting a valid and un-expired JWT are given a new session. If they log-out and -in, they are switched to the new system. If they don't, they will be switched once their existing JWT expires (max 1 week). Then after all the JWT are expired, change the `validate` method to remove the JWT branch.

### Pros
- Code changes localised to one area
- Unlikely to lead to missed endpoints

### Cons
- Logic is more complex (temporarily)
- Configuration is more complex (temporarily)

#### Migration under Option 2
The `validate` method is identical to the first branch of Option 1. The new strategy should be positioned as first in the list of strategies for all API routes.

Login route is changed to:
  - Authenticate against the new strategy in `try` mode
  - If request has JWT:
     - Set session ID
     - 200
  - If authenticated with session ID:
     - 200
  - Else evaluate payload:
     - If valid, create new session, set session ID cookie
     - Else 401

Users with a valid and un-expired JWT are allowed to continue using the app. If they log-out and -in, they are switched to the new system. If they don't, they will be switched once their existing JWT expires (max 1 week).

### Pros
- Logic is simpler
- Configuration is simpler?

### Cons
- Code changes spread throughout the code base
- Could lead to missed endpoints

#### Testing Before Deployment
If sessions are not preserved, this is simple.

If sessions are preserved:
- must be authenticated with valid JWT
- must be authenticated with valid session ID
- login with valid JWT must return session ID (regardless of payload)
- login without valid JWT must return session ID
- expired JWT must give 401

If sessions are not preserved:
- must NOT be authenticated with valid JWT
- must be authenticated with valid session ID
- login with valid JWT must return session ID (if payload is correct)
- login with valid JWT must return 401 (if payload is incorrect)
- login without JWT must return session ID
- expired JWT must give 401

## Tasks
Note that not all these tasks are necessary, depending on the result of the business and technical decisions.

1. Setup redis config and connection (1 day)
1. Create new schema (1.5 day)
1. Create new strategy (0.5 days - 1.5 days)
1. Update routes (0 - 1 days)
1. Changes to login handler (1 day)
1. Review (1 day)

Estimate: 5 - 7.5 days

**Comment by astroash** [comment]
@eliascodes can you add a section listing the new architecture being proposed as part of this change

**Comment by eliascodes** [comment]
What new architecture?

**Comment by astroash** [comment]
An outline of how session management will work.

**Comment by eliascodes** [comment]
On login, we'll set a cookie with the session id, which will be used as a key into the server-side session store (in this case redis).

On each subsequent request, the cookie will be read and checked for existence and expiry against the session store, much like is currently done with the JWT.

The session store will contain various metadata about each user's session, including expiry, referrer, domain, etc. On expiry or deletion of the session, this metadata will be written to the postgres database.

**Comment by milski360** [comment]
Am I right in interpreting from the above, that if we don't preserve user sessions, users will have to log back in again (only once)? Sounds like a minor inconvenience to me. But what does it mean for us in terms of our ability to track use - presumably we can't do this retrospectively? I'm edging towards Option 1, but answers to these questions will help.

**Comment by eliascodes** [comment]
> that if we don't preserve user sessions, users will have to log back in again (only once)?

Yes

> Sounds like a minor inconvenience to me

I agree, although I guess it depends on how accounts/passwords are managed in a CB. 

This is only really relevant to the visitor app, where, for example, we know there is one CB where front-of-house staff who are using the visitor app aren't given the account password (or weren't at the time, which was ~Jan 2019).

> But what does it mean for us in terms of our ability to track use - presumably we can't do this retrospectively?

Regardless of which option we choose, we can't track usage retrospectively. All we have at the moment is a record of the times at which a user logs in.

Both options will in theory allow us to track usage from as soon as they are deployed and used by users. The only difference really is in (1) the amount of work they each require and (2) the inconvenience to users they each result in.

**Comment by milski360** [comment]
Thanks for the explanation - let's go with option 1
