### ISSUE TITLE
Bug - Back to dashboard on Create Anon User page 404's

### ISSUE THREAD

**Issue by edwardwptc** [TwinePlatform/twine-monolith#218]
Reproduction Steps

Login to visitor app
Login to admin dashboard
Select Create anonymous user
https://visitor-beta.twine-together.com/admin/anonymous-user

Press "Back to Dashboard" in top left
Takes you to "https://visitor-beta.twine-together.com/cb/dashboard"
"404 page not found". 

Should point to "https://visitor-beta.twine-together.com/admin" instead?

**Comment by mandsmandsmands** [comment]
Additional failure:
1. Login to visitor app
2. Login to admin dashboard
3. Select Create anonymous user
4. Enter Name, Gender and Year of Birth
5. Click Create
6. Click Back to Dashboard 
7. Press "Back to Dashboard" in top left
Actual: "404 page not found".
Expected: "https://visitor-beta.twine-together.com/admin"

**Comment by mandsmandsmands** [comment]
Both test cases retested and passed on Chrome https://twine-visitor-beta-integration.herokuapp.com/admin/anonymous-user
