### ISSUE TITLE
👀 monitor sign in type for visitor apps

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#226]
Monitor whether visitors are using sign in with name or sign in with QR code.

@eliascodes do you want to roll this in with #207?

**Comment by eliascodes** [comment]
I don't think it's related to #207

**Comment by astroash** [comment]
So my solution would have been to add two columns to the `login_event` table:
- `origin` (clientside app login was created)
- `type` (how user signed in)

Then add visitor sign ins to log in this table.

Do you have an outline of how session management will be tracked to see if there is any overlap? I assumed part of session management is to reimagine this table db tracking on sign ins.

**Comment by eliascodes** [comment]
I don't really think we should think of visit logs as "logins" in any real sense. The use of the term "sign in" for visitors is kind of a red herring tbh.

We can add columns to `visit_log` to track how the log was created, the same as we did for `volunteer_hours_log`.

**Comment by astroash** [comment]
> We can add columns to visit_log to track how the log was created, the same as we did for volunteer_hours_log.

I think visitor sign in type should be kept separate to the `visit_log` table. We are currently only have 2 types, but this is subject to change if we add sign in for bulk visitors or similar features.

As this is currently a temporary measure, how about having a separate table:

```sql
table: visit_log_attendance_type

columns:
visit_log_id     FOREIGN KEY
attendance_type  enum attendance_type


```

**Comment by eliascodes** [comment]
There's no point having a table _and_ an enum. One of the two will do.

**Comment by astroash** [comment]
what type would you put in the column `attendance_type`?

**Comment by eliascodes** [comment]
VARCHAR, same as we're doing for region, sector, disability, gender, ethnicity, etc.

**Comment by astroash** [comment]
Maybe my table above was misinterpreted. I am suggesting the table above as a way of storing the visitor logins, rather than this table holding values for a column in the `visit_log` table.

**Comment by eliascodes** [comment]
Ah ok. Is the only reason you don't want to make changes to the `visit_log` table because this seems like a temporary thing, or is there something else?

**Comment by astroash** [comment]
It seems like a temporary thing and sign in methods may change as part of https://github.com/TwinePlatform/twine-visitor/issues/642

**Comment by eliascodes** [comment]
Ok then your suggestion in https://github.com/TwinePlatform/twine-monolith/issues/226#issuecomment-511888263 is fine by me.
