### ISSUE TITLE
Release Pipeline rework

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#238]
Copied from slack:

> **[Current release pipeline]**
> - PR’s are reviewed by devs and merged into staging environment
> - Staging environment is reviewed by QA & any changes requested are merged into staging
> - On approval of PO changes are deployed to production environment
>
>**[Motivation]**
> The above works if we are working one feature at a time. However if various pieces of work take places simultaneously we end up in a situation where unrelated changes are on staging environment and *we are unable to have granular control over what is deployed to production*.
>
> **[Questions]**
> Me and Elias can propose a technical solution for release pipelines but need to confirm the following questions:
> - Do we want to acceptance test minor changes?
>   - Will this run through QA/PO approval or can dev release when it has gone through code review
> - To what level do we want to run regression testing?
>   - Is this being done on new changes?
>   - Do we want to define critical user paths so we have a light weight & in depth test packs for regression testing
>   - Do we want a monthly/bi-monthly regression test of all apps?
> - How do we want to test not user facing changes ie file restructures/dependency updates/refactors

New setup to be discussed

**Comment by astroash** [comment]
Suggested solution:

- Return to production being manually deployed from github master
- Review apps created for each PR (manually/mirrored apps/different buildpack https://github.com/TwinePlatform/twine-monolith/issues/22#issuecomment-514274614)
- Feature branches being created for scheduled release work
- Hotfix branches being created and merged directly into master

**Comment by eliascodes** [comment]
> Return to production being manually deployed from github master

Does this mean we have a staging/dev branch again, like in the diagram I showed you, or are you imagining we wouldn't need this if we have feature branches?

> Review apps created for each PR

I'm happy to go ahead with this but I can imagine that if there's no automated way to do this it will become quite burdensome.

> different buildpack

Specifically on this, I've had a look and it doesn't seem to do anything special. Our current buildpack should support yarn workspaces already.

Everything else sounds fine.

**Comment by astroash** [comment]
> Does this mean we have a staging/dev branch again
I cannot see any use for them in our setup. Can you think of anything I am overlooking?

> if there's no automated way to do this it will become quite burdensome.
Hosted review apps will only be needed if other team members are reviewing work. I imagine this will be less often with the impending team structure changes. 

> Our current buildpack should support yarn workspaces already.
We cannot have review apps as we need `app.json` to live in the root directory. I've not looked into the buildpack, but I wonder whether it has another way to support this as it's made by heroku.

**Comment by eliascodes** [comment]
> I cannot see any use for them in our setup. Can you think of anything I am overlooking?

No I don't think so, just clarifying.

> Hosted review apps will only be needed if other team members are reviewing work. I imagine this will be less often with the impending team structure changes.

Yeah true.

> I wonder whether it has another way to support this as it's made by heroku

It's not made by heroku, it's made by [these guys](https://github.com/blockhq). The buildpack script is a couple dozen lines, all it does is copy a sub-directory to the root-level.

Anyway, let's go for it, manual review apps can just be the (potentially temporary) price we pay.

**Comment by astroash** [comment]
Revised pipeline:

**GitHub workflow**
- Feature branches created for scheduled release work
- Hotfix branches created and merged directly into master
- PRs to be marked with manual testing requirements
    - bullet points in body of PR
    - apps to test
    - flows that will be affected
- PRs should be code reviewed first then manually tested. If this process is strung out and other major work has been merged in the meantime, PRs need to be retested.
- PRs should be clearly marked if they are waiting for a release schedule/comms. Template TBC

**Deployment workflow**
- Heroku `staging` manually deployed from Github `master`
- As part of merging PRs manually check heroku `staging` build and promote to production. This adds to additional security that any unanticipated issues have not occurred. This is to be done immediately after PR is merged. Changes should not stay in staging. 
- On promotion PRs are marked as deployed to production.

**Comment by astroash** [comment]
On second thought, manual deployment is difficult to track on merged PRs. Will look into a githook for PR linked issues.

**Comment by eliascodes** [comment]
This is documented, shall we wait till the webhooks are fixed or shall we close it? @astroash

**Comment by astroash** [comment]
The need for webhooks has potentially been replaced with the deployed column on the kanban board
