### ISSUE TITLE
🚀 Create visitor app for scrub data

### ISSUE THREAD

**Issue by milski360** [TwinePlatform/twine-monolith#252]
Linked to: https://trello.com/c/2PkCOIIl

Create a hosted version of the visitor app connected to the anonymised dataset.

- [x] edit CB admins of the listed CBs so that data can be viewed
- [x] create hosted app

**Comment by Shanozd** [comment]
@astroash, these are the CB's that are most active on the Visitor App

- centre4
- Chill Studios
- The Life Centre Bierley
