### ISSUE TITLE
❓add FAQs to dashboard app

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#254]
Waiting on designs

**Release requirements:**
- review by PO then release, no comms

**Comment by Shanozd** [comment]
Andrews update:
I have updated the Design file (XD) with a FAQ page layout: FAQs page.jpg as well as showing the FAQs item in the navigation: Screenshot 2019-08-06 at 12.44.06.png. The link to the file for Devs is updated: https://xd.adobe.com/spec/d9d42346-b996-4a50-587b-12a19033107c-afe5/

**Comment by Shanozd** [comment]
Andrews update:
I have updated the Design file (XD) with a FAQ page layout: FAQs page.jpg as well as showing the FAQs item in the navigation: Screenshot 2019-08-06 at 12.44.06.png.

@milski360 do you want to review or happy to go ahead with this?

**Comment by Shanozd** [comment]
This is ready to go, please review the designs and let Andrew know if you have any comments
