### ISSUE TITLE
🔐 volunteer app should call logout endpoint

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#258]
Discovered during manual testing of #227 

At the moment when "logging out", the volunteer app simply deletes the token stored in `localStorage`. However, it should first call the logout endpoint so that the session is immediately invalidated on the server too to prevent session replay attacks.

**Comment by astroash** [comment]
- How long does the token stay valid on the server before becoming invalidated?
- Does this affect monitoring stats derived from the session logs?

**Comment by eliascodes** [comment]
> How long does the token stay valid on the server before becoming invalidated?

Configurable. In the PR at the moment I think it's one day (although I think it should probs be longer)

> Does this affect monitoring stats derived from the session logs?

Technically yes, for the volunteer app, sessions will only ever expire even if users "log out". However, people don't really log out of apps anyway, so I don't think this would significantly distort the stats.
