### ISSUE TITLE
Minor copy changes

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#278]
- [ ] Remove twine logo from register (unless it looks weird)
- [ ] Get rid of login fields placeholders
- [ ] Change "dashboard" to "your contribution"
- [ ] Change "your hours" to "you gave..."
- [ ] Add what time period the dashboard stats are calculated over
- [ ] Change "view volunteers" to "volunteers" on the nav element

**Comment by milski360** [comment]
Release = all vol app changes released together -1 PO approval required
