### ISSUE TITLE
Estimate effort for "general" project changes to volunteer app

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#282]
Scope the following changes:

> Show the 'General' project to the Admin from the start with explanation text below instead of the date – which is not relevant to this project since it's a default.

> The presence of this generic project helps onboard the admin as to how there can be a default project if they don't want to create or use custom ones. Don't have Edit and Delete icons because the default general project cannot be changed or removed.

Also show "General" project by default on both add log and edit log views.

**Comment by eliascodes** [comment]
Two options for implementation:
1. Client-side only
2. Server-side

### Option 1:
* Keep `volunteer_hours_log.volunteer_project_id` as a nullable column, where a `NULL` value is interpreted as no project being assigned to that log.
* On the "Projects" view of the volunteer app, "general" is prepended to the list of projects by client-side code
* On the "Add log"/"Edit log" (`VOLUNTEER`) view of the volunteer app, the "Projects" field is only displayed if some non-general projects exist
* On the "Add log"/"Edit log" (`VOLUNTEER_ADMIN`) view of the volunteer app, the "Projects" field is displayed

**Comment by astroash** [comment]
> Option 2

I think this a is a bad idea. We should not mirror representations of `null` values in the database. This would also involve amending previously added data.

> These are for initial dev work only, not including review and deployment:

I don't think this is a useful way to scope work as it gives unrealistic expectations to the rest of the team. reviewing & manually testing is easily the longest part of the process.

**Comment by astroash** [comment]
Re our conversion yesterday on supporting old and new versions of the native app. This would be a good use case for API versioning, the new app can use v1.1 routes for volunteer logs to ensure we do not cause any inconsistencies

**Comment by eliascodes** [comment]
### Option 3
#### API
- Add minor incremented API version (1.1)
- For all endpoints returning `VolunteerLog` objects in v1.1, ensure `project: null` values are replaced with `project: "General"` values (for example, in `VolunteerLogs.serialise`

#### Volunteer App
- Update to target API v1.1
- On the "Projects" view of the volunteer app, "general" is marked as non-editable
- On the "Add log"/"Edit log" (VOLUNTEER) view of the volunteer app, the "Projects" field is only displayed if some non-general projects exist. The "general" project for that CB is the default value.
- On the "Add log"/"Edit log" (VOLUNTEER_ADMIN) view of the volunteer app, the "Projects" field is displayed. The "general" project for that CB is the default value.

#### Dashboard
- No substitutions needed

### Updated Estimates
Including reviews/testing, ignoring Dashboard work (deferred):
- Option 1: 3 days
- Option 2: 5 days
- Option 3: 6 days

**Comment by astroash** [comment]
On reflection I think that **option 1** is the best for us to move forward with **if we force reinstall with the platform switch over**:
- the changes to the volunteer app are short lived so I think it's fine for us to handle this clientside for the time being
- as previously mentioned **option 2** has the potential to introduce breaking changes and should be avoided
- the model methods of **option 3** can be integrated as part of the switch over and we will not have to create a api bump

If we **do not** force reinstall with the platform switch over then completing **option 3** now will save us time in the future.

Realistically I think **option 1** will take closer to 4 days as review/testing/amending is a long process.

**Comment by eliascodes** [comment]
> force reinstall with the platform switch over

Does this mean we prevent the old app from working, or just tell everyone to upgrade via comms? If the former, how specifically were you thinking of doing this? Adding (for e.g.) a header to the requests from the new app and only serving those?

**Comment by astroash** [comment]
> Does this mean we prevent the old app from working

It's worth us considering if this is worthwhile, or phasing it out by moving to a completely new api version number, n monitoring old api usage before deprecating. I would like to avoid the situation where we are handling specific version numbers for specific routes, as this will be difficult to maintain n rely on our memory of which routes are relevant to which app.

**Comment by eliascodes** [comment]
IMO I think given what the usage numbers are, we should aim for the minimum disruption possible to end users (which I think means we support old versions of the app, and go with option 3). 

I reckon @edwardwptc can probably advise better on what users would be willing to tolerate. Specifically, if we make it so that once the new app is released, users are unable to use the old app and must update it, would be something that is likely to result in a drop in usage?

**Comment by edwardwptc** [comment]
I think with regards to maintaining a userbase, and for simplicity's sake, supporting the older version might make sense, but only if it's perpetual, i.e. will not cause problems in the future.

If we are going to say "This app needs to be uninstalled and reinstalled, we updated it!", at some point, we might as well do so now to keep things less complicated.

But I can't guarantee it won't cause user drop-off. But that's also a bigger conversation; I don't think user drop off is actually a real thing, I think organisation drop off is. If an org stops requiring volunteers to use Twine, that's absolutely a big drop off, but as long as the org is promoting use I don't think "drop off" from the end user perspective is real. 

If they open a volunteer app they have to use to log their hours at a CB they care about and it says "We've updated this, but it means you need to reinstall it! Please do so now, we don't support this old version anymore!" they are either going to A. Do it or B. Ask a staff member for help. If the org is engaged properly, they'll do it, and it should be simple. 

I'm happy to comms with orgs about the change happening. If we want to go super safe, just support the outdated version, but again only if the above isn't going to happen x months into the future anyway, in which case we should get it out of the way.

**Comment by astroash** [comment]
I'm back on ⓣⓔⓐⓜ **OPTION 3**, with the addition:

- upgrade all apps to v1.1
- monitor the usage of v1
- deprecate v1 when it is no longer in use.

**Comment by eliascodes** [comment]
Superseded by #325 #326
