### ISSUE TITLE
Create user session reports

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#323]
Define requirements for user session reports (i.e. statistics to be calculated).

**Comment by eliascodes** [comment]
Example of fields in a potential data dump. This is the simplest example, with no significant aggregations performed:
- user id
- user name
- organisation name
- session start time
- session end time
- session end type (log out or expiry)
- app used
- pages visited
- device used

@milski360 if you'd like specific statistics or aggregates to be calculated, please describe them. For example:
- average session length per user
- average users per app (per time period)
- unique users per app page (only for visitor app and dashboard)
- etc.

Once we agree the structure of the CSV, we can implement this.

**Comment by milski360** [comment]
Thanks @eliascodes. Actually these are pretty much spot on, so let's proceed with the variables you've listed and the 3 calculations you've suggested. We can then review if needed, but I think this will give us plenty to get started with!
