### ISSUE TITLE
📊 Improve visits data visualisation

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#324]
https://trello.com/c/qKgUmUVV

Requirements to be detailed

Epic:
https://docs.google.com/document/d/1IjnjKjj7jcefzRquLFj7kZOK4MK5nFAwsmIIR2qMWbM/edit#heading=h.9gujobhjuts7

**Comment by milski360** [comment]
I was compiling the tech requirements for this, and realised that there is potentially more to this than I first thought (e.g. we haven't factored in time periods being referenced, or whether we are measuring visits or visitors). Here's an updated user story, using Andrew's designs: https://docs.google.com/document/d/1SbUYnHCJH8W1yB7gdwJadrdoqQEByxtRd_8xc5BW1AY/edit?usp=sharing. Let's discuss on Mon

**Comment by eliascodes** [comment]
I think this is an opportunity to simplify the `VisitsData` component.

Proposed changes:
1. Stop using `GET /community-businesses/me/visit-logs/aggregates`
  - Instead, use `GET /community-businesses/me/visit-logs`
  - Add `since` and `until` query params to this endpoint
  - Process the logs client side like we do on the dashboard (the stats are very simple using `collectBy`)
2. Remove `getActivitiesForChart`, `getGendersForChart`, etc in favour of a single function (they all do the same thing basically).
3. Re-structure state
4. Use `react-flexbox-grid` instead of old custom layout components

This is over and above the changes required by the user story.

On (3), I'm imagining the following:
```
{
  data: { // actual data to feed to charts
    gender: {},
    age: {},
    time: {},
    activity: {},
    category: {},
  },
  charts: { // chart options (e.g. for changing step size)
    category: { stepSize: 2 },
    time: { stepSize: 2 },
  },
  options: { // select options
    genders: [],
    activities: [],
  },
  filters: { // filters
    gender: '',
    age: '',
    time: '',
    activity: '',
  },
  errors: {},
}
```

**Comment by eliascodes** [comment]
@astroash I'm going to assume the above is fine unless you raise something. If the changes that were discussed at the meeting yesterday change any of the above significantly I'll post an update.

**Comment by astroash** [comment]
@eliascodes changes look good. Can we please not use `react-flexbox-grid`. This library enforces padding which is difficult to style with without overriding with `!important`
