### ISSUE TITLE
☁️ Changes to log duration capturing

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#367]
This is a place to discuss options for how we store volunteer logs. Client side app will be changing from collecting duration to collecting start and end times. For data analysis it would be useful to differentiate between logs which specified duration and those which specified start and end times.

**Comment by eliascodes** [comment]
Seems to still be under discussion. Re-posting Edward's comment:

> Hi all. I've spoken to a few people recently about the prospect of having "number of hours" and "number of minutes" changed to "Start time" and "End time". When this was originally proposed I was keen, the basic idea being that it's simpler (no maths in people's heads, just two times) and provided richer data (since we could then track time against time of day rather than just date). I have since thought that it makes it moderately more complex in the following situations: If you are an admin adding historical logs for someone last week, you might not know what times they arrived, (but of course they can input approximates, but that limits the accuracy of the overall data) and if admins are inputting bulk logs for volunteer there is lower potential for overlap, i.e. 3 people all did 2hrs on Monday under the current system, with the new start and end times all 3 would have had to have arrived and left at the same time to avoid duplication.

**Comment by astroash** [comment]
closing due to feature idea being dropped. Continue with adding hours & minutes.
