### ISSUE TITLE
Visits charts feedback

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#394]
We received from feedback from Jake and Stephen.

> In the dropdown list for 'Activities', what does 'project activity' mean?

Everything in that list is a user defined activity. You can confirm this by going to the activities page in the admin section.

> The colours switch in the charts when applying filters. For example, male goes from purple to yellow when filtering by Gender or Activity. Same thing happens to the Age chart too. If possible, would like us to keep consistent colours

To be actioned.

> We also previously discussed using the same colour palette as the vol app chart, which can handle multiple categories. Has this been applied? It's not clear how the demographics charts looks when loaded with multiple age groups

To be addressed in a separate issue. See #395.

> Visits by time chart would be better above the 'reasons for visiting' chart if possible, as this is probably the more useful info for CBs

To be actioned.

> Could we align the Y axes on the two charts? I think it might look slightly neater than having them offset from one another

Possibly. Will investigate if this is functionality that is exposed by our chart library.

> On the ‘Reasons for Visiting’ chart, where an activity has only 1 or 2 entries (as is the case for ‘Skill share’ and ‘Digital share’ – the bar is very small. Are there any small adjustments we can make to the scale to increase those sizes or are we limited by the upper range numbers?

If I follow what you're saying, are you suggesting that we have a non-linear x-axis?

> The charts run very close to the bottom of the screen, and it makes it look like there might be more to see below the fold – could we add a little more padding under the charts at the bottom?

To be actioned.

> Add initial caps for “Male”, “Female” and “Prefer not to say” so we are consistent across our labelling

To be actioned.

> ‘Prefer not to say’ data is in grey, but we also have a small white separation between sections on the pie charts, which makes it a little difficult to see. Could we choose a different third colour? One which more contrast to the white?

To be actioned. Related to colour palette selection in general.

> Not been able to login on Chrome (though this might have been after you changed the password) – what browsers are we using for testing?

We currently only explicitly support Chrome, but it should work fine on Firefox too (my main browser). Safari sometimes has problems on the QR scanning page. We've never tried it on IE/Edge.

I've been able to log in on both Chrome and Firefox, so I imagine it'll just be because I changed the password. Do you have access to LastPass?

> Export function not working for me – is it supposed to work on this version?

It should work. In what way is it not working?

> I’m not sure we need to have “Dates:” before the date range? I think we can just display the dates themselves

To be actioned.

### Summary of actions on dev
- [x] Remove "Dates:"
- [x] Darken "Prefer not to say" colour
- [x] Consistent capitalisation of gender labels
- [x] Add padding to bottom of charts
- [x] Swap "Reasons for visiting" chart with "Visits by time"
- [x] Prevent colours switching when changing applied filters

**Comment by PM-Jake** [comment]
Thanks for this Elias - just a couple of things I want to check.

'Project Activity' is just a user entered value? 

On the Axes question, I'd be nervous about using a non-linear axis, as it reduces the visual impact of the chart. Perhaps we could just increase the size of the 'mouse-over' area for the lower values, that way the user would be able to interact with the smaller bars without having to increase their size? Happy to talk about some options for this one.

Re: browsers -  Let's revisit this separately in a broader tech conversation. I'll look to set up something soon and we can run through a few things. 

Haven't been able to login this morning (see Slack for LastPass issue), but when I was trying to Export function yesterday, nothing was happening when I clicked the button. I was testing in Edge at that point, not Chrome though.

**Comment by eliascodes** [comment]
> 'Project Activity' is just a user entered value?

Yes

> On the Axes question, I'd be nervous about using a non-linear axis, as it reduces the visual impact of the chart. Perhaps we could just increase the size of the 'mouse-over' area for the lower values, that way the user would be able to interact with the smaller bars without having to increase their size? Happy to talk about some options for this one.

I'd agree that non-linear axes are a bad idea in this case. I can look into what can be done with the mouse-over area. Note that since we're using a chart library, we're a little restricted in how much these charts can be customised.

**Comment by PM-Jake** [comment]
Re: non linear axes. The mouse over area is definitely a nice-to-have, I wouldn't have thought it was crucial to fix it, but good if we can.
