### ISSUE TITLE
🎨 Colours on the visits charts

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-monolith#395]
Based on feedback in #394

> We also previously discussed using the same colour palette as the vol app chart, which can handle multiple categories. Has this been applied? It's not clear how the demographics charts looks when loaded with multiple age groups

Assuming you mean "the same colour palette as the dashboard charts". 

Are you suggesting using this palette for the bar charts, the doughnut charts, or both? 

I think the bar charts would not be improved by using colours other than the Twine purple.

I've attached shots of a number of different options:

### Looping over the same 3 colours
![Screenshot 2019-11-07 at 16 31 07](https://user-images.githubusercontent.com/12719553/68409865-c2450900-017f-11ea-8708-01bdc1984ba2.png)

### Colour palette option 1
![Screenshot 2019-11-07 at 16 38 53](https://user-images.githubusercontent.com/12719553/68409932-e1439b00-017f-11ea-8dc6-783cd503d449.png)

### Colour palette option 2
![Screenshot 2019-11-07 at 16 39 39](https://user-images.githubusercontent.com/12719553/68409971-ebfe3000-017f-11ea-9273-f7894fed6429.png)

### Colour palette option 3
![Screenshot 2019-11-07 at 16 40 27](https://user-images.githubusercontent.com/12719553/68409999-f3bdd480-017f-11ea-862b-275197294175.png)

### Colour palette option 4
![Screenshot 2019-11-07 at 16 41 09](https://user-images.githubusercontent.com/12719553/68410017-f91b1f00-017f-11ea-9b67-a3f707a62943.png)

### Colour palette option 5
![Screenshot 2019-11-07 at 16 41 43](https://user-images.githubusercontent.com/12719553/68410039-ff110000-017f-11ea-9401-34c9a1e8a4f4.png)

Personally, I'm not sure introducing new colours outside of the yellow/purple/grey/white colour palette of the visitor app wins us much legibility beyond the first option of looping the three colours. However my sense of design is not great, and I may be discounting people who find charts harder to read than I do, so I'm happy to go with whatever your preferences are.

**Comment by milski360** [comment]
@eliascodes thanks for this. Yes, I meant the pie charts, as colour differentiation doesn't seem necessary for the bar charts. Option 4 probably works best, though could change one of the purples to the Twine brand purple? Might limit the visual impact when switching tabs to the bar charts. If not possible, keep as it is per current Option 4. 

The colour differentiation will help non-specialists plus futureproof if we ever decide to expand what we visualise (e.g. see ONS advice here: https://style.ons.gov.uk/category/data-visualisation/using-colours/#using-colour-to-connect-information)
