### ISSUE TITLE
remove location reminders

### ISSUE THREAD

**Issue by King-Mob** [TwinePlatform/twine-monolith#599]

**Comment by edwardwptc** [comment]
Hiya, 

We'd like to hold on off this after internal discussion. They still definitely don't work currently on the test app (volunteer and admin). There may be potential to simply remove them, but we would need to know first whether they are being used. 

Is it possible for you guys to pull any kind of metrics about this from the live app re: how many people have location reminders turned on? Feel free to email me if so.
