### ISSUE TITLE
🐛 special characters in CSV download (activity names)

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-monolith#99]
> VOL-DASH-007-0009
Steps: View the table under Time- intial default view of VOL-DASH-007.  Click download button
Expected:  Expecting to see Helping with raising funds (shop, events...)
Actual:  Value is shown:  Helping with raising funds (shop, eventsâ€¦)

**Comment by astroash** [comment]
@mandsmandsmands can you supply a full page screenshot for this error?

**Comment by mandsmandsmands** [comment]
sorry should add - 
Steps: View the table under Time- intial default view of VOL-DASH-007.  Click download button. **Open download in Excel (which is what most users would be using)**

defect18_chars.jpg in https://drive.google.com/open?id=1jc8Qb3wg09SlLlZmoRgV-3igeDQH_tX8

**Comment by astroash** [comment]
Excel doesn't natively support UTF-8 encoded csv files.

Deprioritising as this is a larger fix than initially thought.
